[package]
name = "rust_lib_frinda"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
whisper-rs = "0.13.0"
anyhow = "1.0.94"
hound = "3"